version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - APP_CONFIG_PATH=/data/config/config.json
    ports:
    - "9070:5000"
    volumes:
    - ../pload-config:/data/config
    external_links:
    - postgres
    depends_on:
    - elasticsearch
  elasticsearch:
    image: elasticsearch:7.8.0
    environment:
    - discovery.type=single-node
